// Setting userId global var
//@userId = "{{$random.uuid}}"
@userId = {{$random.uuid}}

###

// Call AddCategory function to create new category
# @name AddCategory
# @timeout 600
POST http://localhost:7275/api/category/add
Content-Type: application/json

{
  "UserId": "{{userId}}",
  "Title": "TestCategory",
  "Description": "Test category for local api check",
  "ParentCategoryId": null
}

> {%
    // Save newly added categoryId to the global var
    client.global.set("guid", response.body); 
%}

###

# @name CheckCategoryWasAdded
# @timeout 600
// Check that recently created category was really added
GET http://localhost:7275/api/category/getById/{{userId}}/{{guid}}

###

# @name DeleteCategory
# @timeout 600
// Clear test data
DELETE http://localhost:7275/api/category/remove/{{userId}}/{{guid}}

###

# @name CheckCategoryWasDeleted
# @timeout 600
// Check that recently created category was really added
GET http://localhost:7275/api/category/getById/{{userId}}/{{guid}}
