services:
  costmanager.transactionservice.api:
    container_name: transactions-service
    image: transactions-service
    build:
      context: .
      dockerfile: CostManager.TransactionService.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "443:443"
      - "80:80"
    
    # Environment section is used for CONTAINER ONLY, docker compose don't know about these env vars
    # and just pass them to the container environment. Docker compose uses .env file when it is need
    # to resolve template's $PLACEHOLDERS
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USER_SECRETS: "/root/.microsoft/usersecrets/5271319f-f1e2-4932-a5f2-01a64ad3ab3b"
      USER_SECRETS_ID: "5271319f-f1e2-4932-a5f2-01a64ad3ab3b"
      
    # $VARs are got from the .env file
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID:$DOTNET_USER_SECRETS