name: Azure Container Apps Deploy for DEV environment

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

env:
  AZURE_CONTAINERREGISTRY_NAME: 'categoryServiceRegistry'   # set this to your function app name on Azure
  AZURE_CONTAINERAPP_PACKAGE_PATH: './CategoryService/Web.API.CategoryService'
  AZURE_CONTAINERAPP_RESOURCEGROUP_NAME: 'category-group-dev'
  AZURE_CONTAINERAPP_NAME: 'category-service-app'
  IMAGE_NAME: 'categoryserviceregistry.azurecr.io/category-service:last'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
           auth-type: IDENTITY
           client-id: ${{ secrets.AZURE_CATEGORY_SERVICE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_CATEGORY_SERVICE_SUBSCRIPTION_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Build and push image
          id: build-image
          run: |
           az acr build --image ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/category-service-app-dev:${{ github.sha }} --registry ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }} --file "Dockerfile" .