name: Transactions service deploy for DEV environment

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

env:
  acrName: '${{ vars.AZURE_COMMON_ACR_NAME }}'
  # Should be updated after container app will be deployed
  containerAppName: '${{ vars.AZURE_TRANSACTION_SERVICE_APP_NAME }}'
  resourceGroup: '${{ vars.AZURE_TRANSACTION_SERVICE_RG_NAME }}'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: dev
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v2
          with:
            # Github application registration client id
            client-id: ${{ secrets.AZURE_APPLICATION_REGISTRATION_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Azure CLI script
          uses: azure/cli@v2
          with:
            azcliversion: latest
            inlineScript: |
              az account show
              az resource list

        - name: Build and push image
          id: build-image
          run: |
            pushd './CostManager.TransactionService'
            az acr build --image ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/dev-transactions-service-app:${{ github.sha }} --registry ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }} .
            popd

        # Move transactions service container app to the transactions rg instead of category rg
        - name: Deploy Container App
          id: deploy-image
          run: |
            az containerapp update --name ${{ env.transactionsServiceAppName }} --resource-group ${{ env.categoryServiceRg }} --image ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/dev-transactions-service-app:${{ github.sha }}

        # Move transactions service container app to the transactions rg instead of category rg
        # UNBLOCK WHEN AZURE CONTAINER APP WILL BE DEPLOYED
        #- name: Build and deploy Container App
        #  uses: azure/container-apps-deploy-action@v1
        #  with:
        #    acrName: ${{ env.acrName }}
        #    containerAppName: ${{ env.transactionsServiceAppName }}
        #    resourceGroup: ${{ env.categoryServiceRg }}
        #    imageToDeploy: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/transactions-service-app-dev:${{ github.sha }}