name: Transactions service deploy for DEV environment

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

env:
  acrName: '${{ vars.AZURE_COMMON_ACR_NAME }}'
  containerAppName: '${{ vars.TRANSACTIONS_SERVICE_APP_NAME }}'
  resourceGroup: '${{ vars.TRANSACTION_SERVICE_RG }}'
  DOTNET_VERSION: '6.0.x'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: dev
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v2
          with:
            # Github application registration client id
            client-id: ${{ secrets.AZURE_APPLICATION_REGISTRATION_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        # FOR LOGS PURPOSES ONLY
        - name: Azure CLI script
          uses: azure/cli@v2
          with:
            azcliversion: latest
            inlineScript: |
              az account show
              az resource list

        - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}

        - name: Run Unit tests
          run: |
            pushd './CostManager.TransactionService/CostManager.TransactionService.UnitTests'
            dotnet test
            popd

        - name: Build and push image
          id: build-image
          run: |
            pushd './CostManager.TransactionService'
            az acr build --image ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/dev-transactions-service-app:${{ github.sha }} --registry ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }} .
            popd

        - name: Deploy Container App
          id: deploy-image
          run: |
            az containerapp update --name ${{ env.containerAppName }} --resource-group ${{ env.resourceGroup }} --image ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/dev-transactions-service-app:${{ github.sha }}

        # UNBLOCK WHEN AZURE CONTAINER APP WILL BE DEPLOYED
        #- name: Build and deploy Container App
        #  uses: azure/container-apps-deploy-action@v1
        #  with:
        #    acrName: ${{ env.acrName }}
        #    containerAppName: ${{ env.containerAppName }}
        #    resourceGroup: ${{ env.resourceGroup }}
        #    imageToDeploy: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/transactions-service-app-dev:${{ github.sha }}